# Generated by Django 5.0.6 on 2024-05-22 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.profile')),
                ('language', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_max', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            bases=('users.profile',),
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.profile')),
                ('specialties', models.TextField()),
                ('resume', models.TextField()),
                ('certificate', models.FileField(upload_to='certificates')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            bases=('users.profile',),
        ),
    ]
