# Generated by Django 5.0.6 on 2024-05-22 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_teacher'),
        ('reviews', '0002_alter_review_student'),
        ('schedules', '0002_alter_schedule_teacher'),
        ('users', '0003_studentprofile_teacherprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
